service: hello-world-java11

provider:
  name: aws
  runtime: java11
  region: eu-central-1
  profile: serverless-admin
  stage: dev
  environment:
    GLOBAL_SECRET: 'Duke is cool'

package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
    environment:
      FUNCTION_SECRET: 'Hello World from Serverless Environment Variables'
  short-timeout:
    handler: com.serverless.ShortTimeout
    memorySize: 256
    timeout: 3

plugins:
  - serverless-offline-ssm
