spring:
  application:
    name: Spring Boot 2 Book
example:
    the-greeting: "Hello, World!"
    precision: 42.23
    servers:
        - name: "springbootbuch"
          url: "http://springbootbuch.de"
    interval: 11
logging:
  path: logs
  pattern:
    level: user:%X{user} %5p
  config: logtofileonly.xml
server:
  tomcat:
    basedir: tc
    accesslog:
      enabled: true
      pattern: \%h %l %u %t \"%r\" %s %b
      prefix: access
      suffix: .log