spring:
  application:
    name: Spring Boot 2 Book
  security:
    user:
      name: philip
      password: "{bcrypt}$2a$10$LVSXeub.faU.nO7VRuYzgud7Uj.kVAu5XajVAGDU.8huZ/m0BWlBO"
      roles: USER, ADMIN
  h2:
    console:
      enabled: true
example:
    the-greeting: "Hello, World!"
    precision: 42.23
    servers:
        - name: "springbootbuch"
          url: "http://springbootbuch.de"
    interval: 11
logging:
  path: logs
  pattern:
    level: user:%X{user} %5p
server:
  tomcat:
    basedir: tc
    accesslog:
      enabled: true
      pattern: \%h %l %u %t \"%r\" %s %b
      prefix: access
      suffix: .log
management:
  endpoints:
    web:
      exposure:
        include: '*'
    jms:
      exposure:
        include: '*'
info:
  description: "@description@"
  organization: "@organization.name@"
  greeting: "Hello, Reader!"