spring:
  application:
    name: Spring Boot 2 Book
example:
    the-greeting: "Hello, World!"
    interval: 1000
    precision: 42.23
    servers:
        - name: "springbootbuch"
          url: "http://springbootbuch.de"