spring:
  datasource:
    url: @build.datasource.url@
    username: @build.datasource.username@
    password: @build.datasource.password@
  flyway:
    enabled: true
  test:
    database:
      replace: none
  jooq:
    sql-dialect: POSTGRES