spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    initialization-mode: embedded
    continue-on-error: false
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
  jpa:
    hibernate:
      ddl-auto: validate
  jta:
    log-dir: jta